baseURL: "https://gupta-puru.github.io/website" 
title: Puru Gupta
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
taxonomies:
    tag: tags

menu:
    main:
        
        - name: Research
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Warwick
          url: https://warwick.ac.uk/fac/soc/economics/staff/pgupta/
          weight: 6

params:
    description: "I am a PhD candidate in Economics, at the University of Warwick, affiliated with the Stochastic Finance research group."
    author: Puru Gupta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","teaching","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Puru Gupta
          subtitle: "I am a PhD candidate in Economics, at the University of Warwick, where I am affiliated with the **Stochastic Finance** research group. My research focuses on optimal risk management and derivative pricing in financial markets dominated by large institutional investors. **I will be on the job market in 2024/2025.**"
          imageUrl: "Puru.jpeg"
          imageWidth: 180
          imageHeight: 210
          imageTitle: Puru Gupta
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: teaching/
            - name: Job Market Paper
              url: papers/paper3
            - name: Curriculum Vitae
              url: Puru-CV.pdf
            - name: Warwick
              url: https://warwick.ac.uk/fac/soc/economics/staff/pgupta/

    socialIcons:
        - name: Linkedin
          url: https://www.linkedin.com/in/puru-gupta-b873008a/
        - name: Email
          url: mailto:puru.gupta.1@warwick.ac.uk
        - name: CV
          url: Puru-CV.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ZwfVefEAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/gupta-puru
       
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Puru Gupta"
      icon: Arms_of_the_University_of_Warwick.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
